-- Shared Music Room: режим "только владелец загружает"
-- 1) Сначала создай пользователя в Supabase:
-- Authentication -> Users -> Add user
-- Скопируй его User UID и вставь вместо YOUR_ADMIN_USER_UUID ниже.
--
-- 2) ВАЖНО: не используй Secret key в браузере. В JS нужен только Publishable key.

create table if not exists public.tracks (
  id bigint generated by default as identity primary key,
  title text not null,
  artist text not null default 'Неизвестный исполнитель',
  audio_url text not null,
  cover_url text,
  created_at timestamptz not null default now()
);

alter table public.tracks enable row level security;

-- Убираем старое публичное право на загрузку.
drop policy if exists "Anyone can add tracks" on public.tracks;

-- Старое/новое чтение: слушать могут все.
drop policy if exists "Anyone can read tracks" on public.tracks;
create policy "Anyone can read tracks"
on public.tracks for select
to anon, authenticated
using (true);

-- Добавлять записи может только твой Auth user.
drop policy if exists "Only admin can add tracks" on public.tracks;
create policy "Only admin can add tracks"
on public.tracks for insert
to authenticated
with check (auth.uid() = 'b224057d-72b0-4492-9c6b-204f8e8045ca'::uuid);

-- Storage: читать музыку могут все, загружать — только владелец.
drop policy if exists "Public can upload music" on storage.objects;
drop policy if exists "Public can read music" on storage.objects;

create policy "Public can read music"
on storage.objects for select
to anon, authenticated
using (bucket_id = 'music');

create policy "Only admin can upload music"
on storage.objects for insert
to authenticated
with check (
  bucket_id = 'music'
  and auth.uid() = 'b224057d-72b0-4492-9c6b-204f8e8045ca'::uuid
);

-- Realtime для списка песен.
alter publication supabase_realtime add table public.tracks;
