-- 1) Создай таблицу tracks и выполни этот SQL в Supabase -> SQL Editor.
create table if not exists public.tracks (
  id bigint generated by default as identity primary key,
  title text not null,
  artist text not null default 'Неизвестный исполнитель',
  audio_url text not null,
  cover_url text,
  created_at timestamptz not null default now()
);

alter table public.tracks enable row level security;

create policy "Only admin can add tracks"
on public.tracks
for insert
to authenticated
with check (
    auth.uid() = 'b224057d-72b0-4492-9c6b-204f8e8045ca'::uuid
);

create policy "Anyone can add tracks"
on public.tracks for insert
to anon, authenticated
with check (true);

-- Включаем realtime для появления новых песен без обновления страницы.
alter publication supabase_realtime add table public.tracks;

-- 2) Storage:
-- В Supabase открой Storage -> New bucket.
-- Название: music
-- Сделай bucket Public.
--
-- Затем в Storage -> Policies создай политики:
-- INSERT для роли anon и authenticated на bucket_id = 'music'
-- SELECT для роли anon и authenticated на bucket_id = 'music'
--
-- Не публикуй service_role key. В сайте используется только anon public key.
